/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var c=Object.getOwnPropertyDescriptor;var d=Object.getOwnPropertyNames;var f=Object.prototype.hasOwnProperty;var m=(t,e)=>{for(var s in e)o(t,s,{get:e[s],enumerable:!0})},u=(t,e,s,r)=>{if(e&&typeof e=="object"||typeof e=="function")for(let n of d(e))!f.call(t,n)&&n!==s&&o(t,n,{get:()=>e[n],enumerable:!(r=c(e,n))||r.enumerable});return t};var g=t=>u(o({},"__esModule",{value:!0}),t);var h={};m(h,{default:()=>l});module.exports=g(h);var i=require("obsidian"),l=class extends i.Plugin{async onload(){this.registerMarkdownPostProcessor((e,s)=>{let n=setInterval(async()=>{let a=document.getElementsByClassName("metadata-properties-heading")[0];if(a!=null){if(a.classList.contains("is-collapsed")){clearInterval(n);return}a instanceof HTMLElement?a.click():console.error("Heading not clickable")}},1);setTimeout(()=>{clearInterval(n)},100)})}};
